### ISSUE TITLE
Document how to specify examples

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/docs#46]
In this issue - https://github.com/fern-api/fern/issues/1992 - there are peoples asking for documentation on how to specify examples. 

For each type, we should explain how to create an example: 
- objects
- unions
- aliases
- endpoints
- endpoints with errors

**Comment by dannysheridan** [comment]
@dsinghvi take a look at this PR: https://github.com/fern-api/docs/pull/63

Likely need to add more explaining words.

Note: I'm not using consistent examples throughout our Docs. I think that is a "best practice".
